# Generated by Django 5.2.8 on 2025-12-10 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Admin Login'), ('LOGOUT', 'Admin Logout'), ('DATA_ACCESS', 'Data Access'), ('ENCRYPTION', 'Encryption Operation'), ('DECRYPTION', 'Decryption Operation'), ('SECURITY_VIOLATION', 'Security Violation'), ('SESSION_TIMEOUT', 'Session Timeout'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt')], help_text='Type of event being logged', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', help_text='Severity level of the event', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('request_path', models.CharField(blank=True, help_text='URL path that was accessed', max_length=255)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method used (GET, POST, etc.)', max_length=10)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data for the event')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event occurred')),
                ('admin_user', models.ForeignKey(blank=True, help_text='Admin user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='faq_auditlo_event_t_d6f700_idx'), models.Index(fields=['admin_user', 'created_at'], name='faq_auditlo_admin_u_2eb7c4_idx'), models.Index(fields=['severity', 'created_at'], name='faq_auditlo_severit_7fc045_idx'), models.Index(fields=['ip_address', 'created_at'], name='faq_auditlo_ip_addr_5f723b_idx')],
            },
        ),
    ]
