# Generated by Django 5.2.8 on 2025-12-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('current_topic', models.CharField(blank=True, help_text='Current conversation topic', max_length=200)),
                ('language', models.CharField(default='en', help_text='Session language', max_length=10)),
                ('user_preferences', models.JSONField(blank=True, default=dict, help_text='User preferences for this session')),
                ('total_interactions', models.IntegerField(default=0, help_text='Total number of interactions')),
                ('successful_responses', models.IntegerField(default=0, help_text='Number of successful responses')),
                ('average_confidence', models.FloatField(default=0.0, help_text='Average response confidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Session expiration time', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_sessions', to='faq.enduser')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the source document', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of document content', max_length=64)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('updated', 'Updated')], db_index=True, default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('faqs_extracted', models.IntegerField(default=0, help_text='Number of FAQs extracted from document')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('document_metadata', models.JSONField(blank=True, default=dict, help_text='Additional document metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash', 'status'], name='faq_ragdocu_file_ha_dc7ad9_idx'), models.Index(fields=['status', 'created_at'], name='faq_ragdocu_status_98727e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGFAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='FAQ question text')),
                ('answer', models.TextField(help_text='FAQ answer text')),
                ('keywords', models.CharField(blank=True, db_index=True, help_text='Extracted keywords', max_length=512)),
                ('category', models.CharField(blank=True, db_index=True, help_text='FAQ category', max_length=100)),
                ('rag_id', models.CharField(db_index=True, help_text='Unique RAG system identifier', max_length=100, unique=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Extraction confidence score')),
                ('source_section', models.CharField(blank=True, help_text='Document section where FAQ was found', max_length=200)),
                ('question_embedding', models.JSONField(blank=True, help_text='Question embedding vector', null=True)),
                ('answer_embedding', models.JSONField(blank=True, help_text='Answer embedding vector', null=True)),
                ('keywords_embedding', models.JSONField(blank=True, help_text='Keywords embedding vector', null=True)),
                ('embedding_model', models.CharField(blank=True, help_text='Model used for embeddings', max_length=100)),
                ('embedding_version', models.CharField(blank=True, help_text='Embedding model version', max_length=50)),
                ('query_matches', models.IntegerField(default=0, help_text='Number of times matched in queries')),
                ('last_matched', models.DateTimeField(blank=True, help_text='Last time this FAQ was matched', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_faqs', to='faq.ragdocument')),
            ],
            options={
                'verbose_name': 'RAG FAQ Entry',
                'verbose_name_plural': 'RAG FAQ Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGPerformanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('component_name', models.CharField(help_text='Component that triggered the alert', max_length=100)),
                ('metric_name', models.CharField(help_text='Metric that triggered the alert', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('acknowledged', 'Acknowledged')], db_index=True, default='active', max_length=20)),
                ('message', models.TextField(help_text='Alert message')),
                ('current_value', models.FloatField(help_text='Current metric value')),
                ('threshold_value', models.FloatField(help_text='Threshold that was exceeded')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='Who/what resolved the alert', max_length=100)),
                ('resolution_notes', models.TextField(blank=True, help_text='Resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_id'], name='faq_ragperf_alert_i_79e7b5_idx'), models.Index(fields=['severity', 'status'], name='faq_ragperf_severit_7ce736_idx'), models.Index(fields=['component_name', 'status'], name='faq_ragperf_compone_d2572a_idx'), models.Index(fields=['status', 'created_at'], name='faq_ragperf_status_5deb47_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('original_query', models.TextField(help_text='Original user query')),
                ('corrected_query', models.TextField(blank=True, help_text='Typo-corrected query')),
                ('intent', models.CharField(blank=True, help_text='Extracted query intent', max_length=100)),
                ('language', models.CharField(default='en', help_text='Detected language', max_length=10)),
                ('response_text', models.TextField(help_text='Generated response text')),
                ('confidence_score', models.FloatField(help_text='Response confidence score')),
                ('generation_method', models.CharField(choices=[('rag', 'RAG Generation'), ('direct_match', 'Direct Match'), ('synthesized', 'Multi-source Synthesis'), ('fallback', 'Fallback Response')], help_text='Response generation method', max_length=20)),
                ('context_used', models.BooleanField(default=False, help_text='Whether conversation context was used')),
                ('processing_time', models.FloatField(help_text='Query processing time in seconds')),
                ('matched_faqs_count', models.IntegerField(default=0, help_text='Number of FAQs matched')),
                ('query_metadata', models.JSONField(blank=True, default=dict, help_text='Additional query metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='faq.ragconversationsession')),
                ('source_faqs', models.ManyToManyField(blank=True, related_name='query_logs', to='faq.ragfaqentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGSystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('confidence_score', 'Confidence Score'), ('success_rate', 'Success Rate'), ('error_rate', 'Error Rate'), ('query_volume', 'Query Volume'), ('system_health', 'System Health')], db_index=True, max_length=50)),
                ('component_name', models.CharField(blank=True, help_text='Component name (if applicable)', max_length=100)),
                ('value', models.FloatField(help_text='Metric value')),
                ('threshold', models.FloatField(blank=True, help_text='Alert threshold (if applicable)', null=True)),
                ('window_start', models.DateTimeField(help_text='Metric window start time')),
                ('window_end', models.DateTimeField(help_text='Metric window end time')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metric metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metric_type', 'created_at'], name='faq_ragsyst_metric__b8a3f7_idx'), models.Index(fields=['component_name', 'metric_type'], name='faq_ragsyst_compone_8d5c72_idx'), models.Index(fields=['window_start', 'window_end'], name='faq_ragsyst_window__111350_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGUserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='User rating (1-5)')),
                ('comments', models.TextField(blank=True, help_text='Optional user comments')),
                ('accuracy_rating', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Response accuracy rating', null=True)),
                ('relevance_rating', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Response relevance rating', null=True)),
                ('helpfulness_rating', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Response helpfulness rating', null=True)),
                ('feedback_metadata', models.JSONField(blank=True, default=dict, help_text='Additional feedback metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='faq.ragquerylog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_feedback', to='faq.enduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ragconversationsession',
            index=models.Index(fields=['session_id', 'last_activity'], name='faq_ragconv_session_02ac8b_idx'),
        ),
        migrations.AddIndex(
            model_name='ragconversationsession',
            index=models.Index(fields=['user', 'created_at'], name='faq_ragconv_user_id_13adb2_idx'),
        ),
        migrations.AddIndex(
            model_name='ragconversationsession',
            index=models.Index(fields=['expires_at'], name='faq_ragconv_expires_fe5b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='ragfaqentry',
            index=models.Index(fields=['rag_id'], name='faq_ragfaqe_rag_id_369334_idx'),
        ),
        migrations.AddIndex(
            model_name='ragfaqentry',
            index=models.Index(fields=['category', 'confidence_score'], name='faq_ragfaqe_categor_eebf07_idx'),
        ),
        migrations.AddIndex(
            model_name='ragfaqentry',
            index=models.Index(fields=['document', 'created_at'], name='faq_ragfaqe_documen_1fb7db_idx'),
        ),
        migrations.AddIndex(
            model_name='ragfaqentry',
            index=models.Index(fields=['query_matches', 'last_matched'], name='faq_ragfaqe_query_m_5f1515_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquerylog',
            index=models.Index(fields=['query_id'], name='faq_ragquer_query_i_94ed50_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquerylog',
            index=models.Index(fields=['session', 'created_at'], name='faq_ragquer_session_43d98e_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquerylog',
            index=models.Index(fields=['confidence_score', 'created_at'], name='faq_ragquer_confide_fcef4f_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquerylog',
            index=models.Index(fields=['generation_method', 'created_at'], name='faq_ragquer_generat_e1fe20_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquerylog',
            index=models.Index(fields=['language', 'created_at'], name='faq_ragquer_languag_34780e_idx'),
        ),
        migrations.AddIndex(
            model_name='raguserfeedback',
            index=models.Index(fields=['rating', 'created_at'], name='faq_raguser_rating_8993c5_idx'),
        ),
        migrations.AddIndex(
            model_name='raguserfeedback',
            index=models.Index(fields=['user', 'created_at'], name='faq_raguser_user_id_c9c4f4_idx'),
        ),
    ]
