# Generated by Django 5.2.8 on 2025-12-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_ragconversationsession_ragdocument_ragfaqentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=100)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Helpful'), (-1, 'Not Helpful')])),
                ('query', models.TextField(help_text='Original user query')),
                ('response', models.TextField(help_text='Bot response that was rated')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='faq.faqentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
