# Generated by Django 4.2.7 on 2025-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0004_chatfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragfaqentry",
            name="audience",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Target audience for the FAQ",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ragfaqentry",
            name="composite_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique composite identifier",
                max_length=500,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="ragfaqentry",
            name="condition",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Specific condition or context",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="ragfaqentry",
            name="intent",
            field=models.CharField(
                blank=True, db_index=True, help_text="User intent", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="ragfaqentry",
            index=models.Index(
                fields=["composite_key"], name="faq_ragfaqe_composi_b5eaba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragfaqentry",
            index=models.Index(
                fields=["audience", "category", "intent"],
                name="faq_ragfaqe_audienc_8da0ff_idx",
            ),
        ),
    ]
