# Generated by Django 4.2.7 on 2025-12-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0005_ragfaqentry_audience_ragfaqentry_composite_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragfaqentry",
            name="composite_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Composite identifier for filtering",
                max_length=500,
                null=True,
            ),
        ),
    ]
