"""
Django settings for faqbackend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
 # Default primary key field type
 # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

import os
from pathlib import Path
from dotenv import load_dotenv
import warnings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Suppress deprecation warning for google.generativeai package
# The package still works but Google recommends migrating to google.genai
# This suppresses the warning until we migrate
warnings.filterwarnings('ignore', message='.*google.generativeai.*')
warnings.filterwarnings('ignore', message='.*deprecated-generative-ai-python.*')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z@r=*#4*)znd(&xd%*pbok1=1otg1coc@qy0ng2$jj0k)r9m4e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = [
    'aibot-sxc2.onrender.com',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'faq',
    'captcha',
]

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'faqbackend.middleware.SimpleCORS',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'faq.audit_middleware.AdminAuditMiddleware',  # Add audit logging middleware
    'faqbackend.middleware.AdminAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  
]

ROOT_URLCONF = 'faqbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'faqbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Indian Standard Time (IST, UTC+5:30)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'assets',
    BASE_DIR.parent,  # allow serving root-level static like chatbot.js
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CAPTCHA settings for admin dashboard authentication (Requirements 4.1)
CAPTCHA_IMAGE_SIZE = (120, 50)
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 5  # minutes
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
CAPTCHA_FILTER_FUNCTIONS = ('captcha.helpers.post_smooth',)
CAPTCHA_WORDS_DICTIONARY = '/usr/share/dict/words'
CAPTCHA_FLITE_PATH = None

# Encryption settings for admin dashboard data protection (Requirements 3.4)
# Encryption service uses Django's SECRET_KEY for key derivation
# Additional security settings for encryption operations
ENCRYPTION_SETTINGS = {
    'ALGORITHM': 'Fernet',  # Using Fernet encryption from cryptography library
    'KEY_DERIVATION': {
        'ALGORITHM': 'PBKDF2HMAC',
        'HASH_ALGORITHM': 'SHA256',
        'ITERATIONS': 100000,
        'SALT': b'faq_admin_dashboard_salt',  # Static salt for consistency
    },
    'AUDIT_LOGGING': True,  # Enable audit logging for encryption operations
}

# Admin dashboard security settings
ADMIN_DASHBOARD_SETTINGS = {
    'SESSION_TIMEOUT_MINUTES': 30,  # Session timeout for admin users
    'MAX_SESSION_DURATION_HOURS': 8,  # Maximum session duration
    'LOGIN_URL': '/admin-dashboard/login/',  # Admin login URL
    'LOGOUT_URL': '/admin-dashboard/logout/',  # Admin logout URL
    'REQUIRE_STAFF_STATUS': True,  # Require staff status for admin access
    'AUDIT_ALL_ACTIONS': True,  # Enable comprehensive audit logging
    'READ_ONLY_ACCESS': True,  # Enforce read-only access to data
}

# Gemini AI Configuration
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") # Set your API key in environment variables

# AI-Enhanced FAQ Settings
AI_FAQ_SETTINGS = {
    'ENABLE_GEMINI': True,  # Enable/disable Gemini AI integration
    'FALLBACK_TO_TRADITIONAL': True,  # Use traditional search if Gemini fails
    'MIN_SEMANTIC_CONFIDENCE': 0.3,  # Minimum confidence for semantic matches
    'MAX_AI_RESULTS': 5,  # Maximum results from AI search
    'CONTEXT_RESPONSE_LENGTH': 200,  # Max length for contextual responses
}

# Logging configuration for admin security events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'admin_security.log',
            'formatter': 'security',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'security',
        },
    },
    'loggers': {
        'admin_security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

CSRF_TRUSTED_ORIGINS = [
    'https://aibot-sxc2.onrender.com',
]
